# Generated by Django 4.2 on 2025-08-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('os_name', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('num_cores', models.IntegerField()),
                ('num_threads', models.IntegerField()),
                ('ram_total_gb', models.FloatField()),
                ('ram_used_gb', models.FloatField()),
                ('ram_available_gb', models.FloatField()),
                ('storage_total_gb', models.FloatField()),
                ('storage_used_gb', models.FloatField()),
                ('storage_free_gb', models.FloatField()),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_info', to='monitor_app.host')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='monitor_app.host')),
            ],
            options={
                'ordering': ['-timestamp', 'pid'],
                'unique_together': {('host', 'timestamp', 'pid')},
            },
        ),
    ]
